[profile.default]
src = "src"
out = "out"
libs = ["lib"]
test = "test"
script = "script"
solc_version = "0.8.20"
evm_version = "shanghai"
optimizer = true
optimizer_runs = 1_000_000
via_ir = false
bytecode_hash = "none"
cbor_metadata = false
fs_permissions = [{ access = "read", path = "./" }]
gas_reports = ["HikariFactory", "HikariPair", "HikariRouter", "HikariTokenFactory", "HikariFeeCollector"]
ffi = false

[profile.default.fuzz]
runs = 1000
max_test_rejects = 100_000
seed = "0x1"

[profile.default.invariant]
runs = 256
depth = 64
fail_on_revert = false
call_override = false
shrink_run_limit = 5_000

[profile.ci]
fuzz = { runs = 10_000 }
invariant = { runs = 1_024, depth = 128 }
verbosity = 2

[profile.intense]
fuzz = { runs = 100_000 }
invariant = { runs = 4_096, depth = 256 }

[fmt]
line_length = 120
tab_width = 4
bracket_spacing = false
int_types = "long"
quote_style = "double"
number_underscore = "thousands"

[rpc_endpoints]
lightchain = "https://rpc.mainnet.lightchain.ai"
lightchain_testnet = "https://rpc.testnet.lightchain.ai"

[etherscan]
lightchain = { key = "${LIGHTSCAN_API_KEY}", url = "https://lightscan.app/api", chain = 9200 }
lightchain_testnet = { key = "${LIGHTSCAN_API_KEY}", url = "https://testnet.lightscan.app/api", chain = 8200 }

